name: Deploy Static Website

# Trigger the workflow when code is pushed to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # The GitHub Actions runner (Ubuntu)

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Configure AWS credentials from GitHub Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this to your AWS region if needed

      # Step 3: Deploy CloudFormation Stack
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file template.yml \
            --stack-name StaticWebsiteStack \
            --capabilities CAPABILITY_NAMED_IAM

      # Step 4: Sync website content to S3 (excluding unwanted files)
      - name: Sync website content to S3
        run: |
          aws s3 sync . s3://my-static-website-${{ secrets.AWS_ACCOUNT_ID }} \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "template.yml" \
            --acl public-read

